added_tailwind+extra_colors
KuzniaCo/browser-game pull request #27
Opened 2020-11-21 21:04 UTC by MaksymilianKeller

Dodałem tailwind i kilka dodatkowych kolorów. W character.ejs trochę poeksperymentowałem i stworzyłem parę pomysłów na stylizację tekstu i ramek w grze.

2020-11-22 18:58 UTC, kkulewski commented on package.json
> +    "build-css": "postcss src/tailwind.css -o public/stylesheets/tailwind.css"
you can change it to run both commands:
`"build": "tsc && postcss src/tailwind.css -o public/stylesheets/tailwind.css",`

2020-11-23 09:38 UTC, bartlomiejmont approved these changes

2020-11-23 15:04 UTC, kkulewski commented
Maybe we should move:
- `views` from `/` to `/src/` (path: `src/views/`)
- `stylesheets` from `/public` to `/src/public` (path: `src/public/stylesheets`) 
and make required adjustmens? Right now we do copy everything to build anyway.

2020-11-23 15:07 UTC, kkulewski requested changes

2020-11-23 15:07 UTC, kkulewski commented on src/app.ts
> +app.set('views', 'build/views');
this doesn't feel right, I think it should be relative path like `'/views'`

2020-11-23 15:07 UTC, kkulewski commented on src/app.ts
> +app.use(express.static('build/public'));
same, more like `'/public`

2020-11-24 17:05 UTC, kkulewski approved these changes

2020-11-24 17:09 UTC, merged